version: '3'

services:
  # MySQL database service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"  # Map host port to container port
    volumes:
      - mysql-data:/home/user/Desktop/BachelorProject/code/Mysql-docker-volume 

  # Golang application service
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map host port to container port
    depends_on:
      - mysql  # Ensure the MySQL container is started before the app

volumes:
  mysql-data: